darts4dorks/user/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField

from darts4dorks.form_utils import UniqueEmailFieldMixin, UniqueUserFieldMixin


class UpdateAccountForm(FlaskForm, UniqueUserFieldMixin, UniqueEmailFieldMixin):
    submit = SubmitField("Update")

darts4dorks/user/__init__.py
from flask import Blueprint

bp = Blueprint("user", __name__, url_prefix="/user")

from darts4dorks.user import routes

darts4dorks/user/routes.py
from flask import render_template, url_for, redirect, flash, request
from flask_login import current_user, login_required
from darts4dorks import db
from darts4dorks.user import bp
from darts4dorks.user.forms import UpdateAccountForm
from darts4dorks.stats import get_rtc_stats


@bp.route("/account")
@login_required
def account():
    stats = get_rtc_stats(current_user.id)
    return render_template("user/account.html", title="Account", data=stats)


@bp.route("/update_account", methods=["GET", "POST"])
@login_required
def update_account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated.", "success")
        return redirect(url_for("user.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template(
        "user/update_account.html", title="Update Account", form=form
    )

darts4dorks/templates/user/account.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid" style="min-height: 80vh; padding-top: 20px; padding-bottom: 20px;">
  <div class="row align-items-center" style="margin-bottom: 20px;">
    <div class="col-md-1 text-center">
      <img src="{{ current_user.avatar(128) }}" alt="User Avatar" class="img-fluid rounded-circle" />
    </div>
    <div class="col-md-9">
      <div class="card bg-light bg-opacity-75 shadow-lg rounded-4 text-center" style="max-width: 200px;">
        <h1>{{ current_user.username }}</h1>
        <p>
          <a href="{{ url_for('user.update_account') }}">Update your account</a>
        </p>
      </div>
    </div>
  </div>

  <div id="error-message" class="text-danger text-center mb-3"></div>
  <div id="chart" style="width: 100%; height: 700px;"></div>
</div>

<script>const data = {{ data | tojson }};</script>
<script src="https://cdn.plot.ly/plotly-3.0.1.min.js" charset="utf-8"></script>
<script src="{{ url_for('static', filename='profile_stats.js') }}"></script>
{% endblock %}

darts4dorks/templates/user/update_account.html
{% extends "base.html" %}
{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 80vh;">
  <div class="card bg-light bg-opacity-80 shadow-lg p-4 rounded-4" style="width: 100%; max-width: 500px;">
    <div class="card-body">
      <h1 class="card-title text-center mb-4">Update Account</h1>
      {{ wtf.quick_form(form) }}
    </div>
  </div>
</div>
{% endblock content %}